theme: jekyll-theme-slate
title: Vaccine Locator
description: Find Covid Vaccination Slots in Bengaluru and other places in India
show_downloads: true
google_analytics: UA-190618649-1
user_url: https://www.geekay.xyz